spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mdmh
    hikari:
      username: root
      password: test1357
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
